trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- script: |
    java -version
    chmod +x gradlew
    ./gradlew :app:assembleRelease --no-daemon
  displayName: 'Build APK'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'app/build/outputs/apk/release'
    artifact: 'release-apk'
  displayName: 'Publish APK Artifact'